WITH
    CLIENTE_COMPLETO
    AS(
SELECT DISTINCT
DOC.PESSOA 'HANDLE CLIENTE',
CONTATOS.EMAIL 'EMAIL GN CONTATOS',
COALESCE(CLIENTE.EMAIL,'') + ',' + COALESCE(CLIENTE.K_EMAIL2,'') + ',' + COALESCE(CLIENTE.K_EMAIL3,'') + ',' + COALESCE(CONTATOS.EMAIL,'') AS 'EMAIL'


FROM FN_PARCELAS A
LEFT JOIN FN_DOCUMENTOS DOC                 ON A.DOCUMENTO = DOC.HANDLE
LEFT JOIN GN_PESSOAS CLIENTE                ON DOC.PESSOA = CLIENTE.HANDLE
LEFT JOIN GN_PESSOACONTATOS CONTATOS        ON DOC.PESSOA = CONTATOS.PESSOA

WHERE 
    A.VALOR > 0
AND 
    DOC.ENTRADASAIDA IN ('S') 
AND 
    DOC.TIPODEMOVIMENTO IN (1, 2)  
AND 
    DOC.DATACANCELAMENTO IS NULL
AND  
    A.DOCUMENTOSUSPENSO = 'N'
AND 
    A.PREVISAO = 'N'
AND
    DOC.PESSOA NOT IN (2237,6873,494,4210,3393,7586,4544,5812,3394,2326) -- Remove a venda entre filiais
AND
    DOC.OPERACAO != 177 --- Remove a operação "2003 - CRE - Adiantamento de Clientes"
AND
    YEAR(DOC.DATAEMISSAO) >= '2022' 
    )

SELECT
*
FROM CLIENTE_COMPLETO